#all common settings

from colorama import Fore, Back, Style, init

MIN_ROWS = 20
MIN_COLS = 30

BOTTOM_GUTTER = 5
RIGHT_GUTTER = 5
TOP_GUTTER = 1

MAXLEN_PADDLE = 100

FRAME_TIME = 0.1

BG_COLOR = Back.BLACK
BG_ACC_COLOR = Back.LIGHTMAGENTA_EX

BG_STAR_PROB = 0.2
MAXVEL_BALL = 10

BLOCK_X_SIZE = 2
BLOCK_Y_SIZE = 10
BLOCK_PROB = 0.75
BLOCK_COLORS = [ Back.WHITE, Back.RED, Back.YELLOW, Back.GREEN ]

